import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";


const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}>
      {children}

      {/* Bottom Navigation */}
      <nav className="fixed bottom-0 left-0 right-0 bg-white border-t">
          <div className="flex justify-around py-2">
              <Link href="/home-parent" className="text-center">
                  <button className="text-center">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"
                           className="w-6 h-6">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 3v18h18V3H3z"/>
                      </svg>
                      <span className="text-xs">Home</span>
                  </button>
              </Link>
              <Link href="/search-parent" className="text-center">
                  <button className="text-center">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"
                           className="w-6 h-6">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v8m-4-4h8"/>
                      </svg>
                      <span className="text-xs">Search</span>
                  </button>
              </Link>
              <Link href="/messages" className="text-center">
                  <button className="text-center">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"
                           className="w-6 h-6">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 10H7v10h14V10z"/>
                      </svg>
                      <span className="text-xs">Messages</span>
                  </button>
              </Link>
              <Link href="/request-my-request" className="text-center">
                  <button className="text-center">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"
                           className="w-6 h-6">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8h18M3 16h18"/>
                      </svg>
                      <span className="text-xs">Request</span>
                  </button>
              </Link>
              <Link href="/home-parent" className="text-center">
                  <button className="text-center">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"
                           className="w-6 h-6">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 14l-4-4-4 4"/>
                      </svg>
                      <span className="text-xs">Profile</span>
                  </button>
              </Link>
          </div>
      </nav>
      </body>
    </html>
  );
}
