services:
  backend:
    build:
      context: /
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/nwdb?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - H2_CONSOLE_ENABLED=true
    depends_on:
          - mysql  # Specifying Dependencies on MySQL Services

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - ESLINT_NO_DEV_ERRORS=true
    command: ["npm", "run", "build"]  # Make sure you only run the next build
    ports:
      - "3000:3000"
    environment:
      - ESLINT_NO_DEV_ERRORS=true

  mysql:
    image: mysql:latest  # Using the Latest MySQL Mirror
    ports:
      - "3306:3306"  # Mapping MySQL ports to hosts
    environment:
      MYSQL_ROOT_PASSWORD: 123456  # Setting the MySQL root user password
      MYSQL_DATABASE: nwdb  # Create a database called nwdb
    volumes:
      - mysql_data:/var/lib/mysql  # Persistent MySQL Data

volumes:
  mysql_data:  # Defining Persistent Volumes